#!/bin/zsh

# This file was generated by go-doc (github.com/AdamSLevy/go-doc), and defines
# a `go` shim function, which overrides the default go binary found in PATH.
# The shim calls `go-doc` in place of `go doc`, but otherwise passes all
# arguments through to the actual go binary. 
#
# Additionally, `go - doc` calls the real `go doc`.
#
# By default the go and go-doc binaries are the ones returned by `which -p`,
# which is the executable found in the PATH. You can explicitly set these
# binaries by setting GOSHIM_GO and GOSHIM_GODOC.

__bin_go() {
  local GO=${GOSHIM_GO:-$(which -p go)}
  "$GO" "$@"
}
__bin_go-doc() {
  local GODOC=${GOSHIM_GODOC:-$(which -p go-doc)}
  "$GODOC" "$@"
}

# go is a shim for the real go which uses go-doc in place of `go doc`
go() {
  case $1 in
    doc)
      shift
      __bin_go-doc "$@"
      return
      ;;
    - | --)
      # If we're being invoked as `go -` or `go --`, then we need to pass the
      # arguments through to the real `go` binary.
      shift
      ;;
  esac

  __bin_go "$@"
}
